# Semgrep Security Rules Configuration
# Custom security rules for Briefly Cloud application

rules:
  - id: supabase-service-key-exposure
    pattern: |
      const $VAR = "$KEY"
    metavariable-regex:
      $KEY: "eyJ[a-zA-Z0-9_-]+\\.[a-zA-Z0-9_-]+"
    message: "Potential Supabase service key exposure. Use environment variables."
    languages: [typescript, javascript]
    severity: ERROR
    
  - id: openai-api-key-exposure
    pattern: |
      const $VAR = "sk-$KEY"
    message: "OpenAI API key detected. Use environment variables."
    languages: [typescript, javascript]
    severity: ERROR
    
  - id: stripe-secret-key-exposure
    pattern: |
      const $VAR = "sk_$KEY"
    message: "Stripe secret key detected. Use environment variables."
    languages: [typescript, javascript]
    severity: ERROR
    
  - id: sql-injection-risk
    patterns:
      - pattern: |
          `SELECT * FROM $TABLE WHERE $FIELD = ${$VAR}`
      - pattern: |
          `INSERT INTO $TABLE ($FIELDS) VALUES (${$VALUES})`
      - pattern: |
          `UPDATE $TABLE SET $FIELD = ${$VAR}`
      - pattern: |
          `DELETE FROM $TABLE WHERE $FIELD = ${$VAR}`
    message: "Potential SQL injection vulnerability. Use parameterized queries."
    languages: [typescript, javascript]
    severity: ERROR
    
  - id: xss-risk-dangerouslySetInnerHTML
    pattern: |
      dangerouslySetInnerHTML={{ __html: $VAR }}
    message: "Potential XSS vulnerability with dangerouslySetInnerHTML. Sanitize input."
    languages: [typescript, javascript]
    severity: ERROR
    
  - id: insecure-random-generation
    patterns:
      - pattern: Math.random()
      - pattern: new Date().getTime()
    message: "Insecure random number generation. Use crypto.randomBytes() for security purposes."
    languages: [typescript, javascript]
    severity: WARNING
    
  - id: hardcoded-credentials
    patterns:
      - pattern: |
          password: "$PASSWORD"
      - pattern: |
          secret: "$SECRET"
      - pattern: |
          token: "$TOKEN"
    metavariable-regex:
      $PASSWORD: "[a-zA-Z0-9]{8,}"
      $SECRET: "[a-zA-Z0-9]{16,}"
      $TOKEN: "[a-zA-Z0-9]{20,}"
    message: "Hardcoded credentials detected. Use environment variables or secure storage."
    languages: [typescript, javascript]
    severity: ERROR
    
  - id: insecure-http-requests
    patterns:
      - pattern: |
          fetch("http://$URL", ...)
      - pattern: |
          axios.get("http://$URL", ...)
      - pattern: |
          axios.post("http://$URL", ...)
    message: "Insecure HTTP request detected. Use HTTPS for all external requests."
    languages: [typescript, javascript]
    severity: ERROR
    
  - id: missing-input-validation
    pattern: |
      export async function $HANDLER(request: NextRequest) {
        const $BODY = await request.json();
        ...
      }
    message: "Missing input validation in API handler. Validate all user input."
    languages: [typescript]
    severity: WARNING
    
  - id: missing-authentication-check
    pattern: |
      export async function $HANDLER(request: NextRequest) {
        ...
      }
    paths:
      include:
        - "src/app/api/**/*.ts"
      exclude:
        - "src/app/api/auth/**/*.ts"
        - "src/app/api/health/**/*.ts"
    message: "API handler missing authentication check. Verify user authentication."
    languages: [typescript]
    severity: WARNING
    
  - id: cors-wildcard-origin
    patterns:
      - pattern: |
          origin: "*"
      - pattern: |
          "Access-Control-Allow-Origin": "*"
    message: "CORS wildcard origin detected. Specify allowed origins explicitly."
    languages: [typescript, javascript]
    severity: ERROR
    
  - id: weak-session-configuration
    patterns:
      - pattern: |
          httpOnly: false
      - pattern: |
          secure: false
      - pattern: |
          sameSite: "none"
    message: "Weak session cookie configuration. Use secure cookie settings."
    languages: [typescript, javascript]
    severity: ERROR
    
  - id: missing-rate-limiting
    pattern: |
      export async function POST(request: NextRequest) {
        ...
      }
    paths:
      include:
        - "src/app/api/**/*.ts"
      exclude:
        - "src/app/api/auth/**/*.ts"
    message: "POST endpoint missing rate limiting. Implement rate limiting for API endpoints."
    languages: [typescript]
    severity: INFO
    
  - id: insecure-file-upload
    patterns:
      - pattern: |
          const $FILE = await request.formData();
      - pattern: |
          fs.writeFile($PATH, $DATA)
    message: "Potential insecure file upload. Validate file types and scan for malware."
    languages: [typescript, javascript]
    severity: WARNING
    
  - id: missing-csrf-protection
    pattern: |
      export async function POST(request: NextRequest) {
        ...
      }
    message: "POST endpoint may be missing CSRF protection. Verify CSRF token validation."
    languages: [typescript]
    severity: INFO
    
  - id: debug-code-in-production
    patterns:
      - pattern: console.log(...)
      - pattern: console.debug(...)
      - pattern: debugger;
    paths:
      exclude:
        - "**/*.test.ts"
        - "**/*.test.js"
        - "tests/**/*"
    message: "Debug code detected. Remove before production deployment."
    languages: [typescript, javascript]
    severity: WARNING
    
  - id: sensitive-data-logging
    patterns:
      - pattern: |
          console.log(..., $VAR, ...)
      - pattern: |
          logger.info(..., $VAR, ...)
    metavariable-regex:
      $VAR: ".*(password|token|secret|key|auth).*"
    message: "Potential sensitive data logging. Avoid logging sensitive information."
    languages: [typescript, javascript]
    severity: ERROR
    
  - id: insecure-jwt-verification
    patterns:
      - pattern: |
          jwt.verify($TOKEN, $SECRET, { verify: false })
      - pattern: |
          jwt.decode($TOKEN, { verify: false })
    message: "Insecure JWT verification. Always verify JWT signatures."
    languages: [typescript, javascript]
    severity: ERROR
    
  - id: missing-input-sanitization
    pattern: |
      innerHTML = $VAR
    message: "Potential XSS vulnerability. Sanitize user input before setting innerHTML."
    languages: [typescript, javascript]
    severity: ERROR
    
  - id: weak-crypto-algorithm
    patterns:
      - pattern: |
          crypto.createHash('md5')
      - pattern: |
          crypto.createHash('sha1')
      - pattern: |
          crypto.createCipher('des', ...)
    message: "Weak cryptographic algorithm detected. Use SHA-256 or stronger."
    languages: [typescript, javascript]
    severity: ERROR
    
  - id: insecure-cookie-settings
    patterns:
      - pattern: |
          res.cookie($NAME, $VALUE, { secure: false })
      - pattern: |
          res.cookie($NAME, $VALUE, { httpOnly: false })
    message: "Insecure cookie settings. Use secure and httpOnly flags."
    languages: [typescript, javascript]
    severity: ERROR
    
  - id: path-traversal-risk
    patterns:
      - pattern: |
          fs.readFile($PATH + $VAR)
      - pattern: |
          fs.readFile(`${$PATH}/${$VAR}`)
      - pattern: |
          path.join($PATH, $VAR)
    message: "Potential path traversal vulnerability. Validate and sanitize file paths."
    languages: [typescript, javascript]
    severity: WARNING
    
  - id: command-injection-risk
    patterns:
      - pattern: |
          exec($CMD + $VAR)
      - pattern: |
          spawn($CMD, [$VAR])
      - pattern: |
          execSync(`${$CMD} ${$VAR}`)
    message: "Potential command injection vulnerability. Validate and sanitize command inputs."
    languages: [typescript, javascript]
    severity: ERROR
    
  - id: missing-error-handling
    pattern: |
      async function $FUNC(...) {
        ...
        await $CALL(...)
        ...
      }
    message: "Missing error handling for async operation. Implement proper error handling."
    languages: [typescript]
    severity: INFO
    
  - id: insecure-redirect
    patterns:
      - pattern: |
          redirect($URL)
      - pattern: |
          NextResponse.redirect($URL)
    message: "Potential open redirect vulnerability. Validate redirect URLs."
    languages: [typescript, javascript]
    severity: WARNING